vendor_upload_handler:
    resource: "@VendorUploadHandlerBundle/Resources/config/routing.yml"
    prefix:   /

vendor_entity_hidden_type:
    resource: "@VendorEntityHiddenTypeBundle/Resources/config/routing.yml"
    prefix:   /entity_hidden_type

